name: tf211
channels:
  - apple
dependencies:
  - python=3.10
  - tensorflow-deps
  - pip:
      - tensorflow-macos==2.11
      - tensorflow_datasets
      - keras_cv==0.4.2
      - numpy==1.24.3
      - marshmallow
      - pycocotools
      - coremltools